# Copyright (c) The OpenTofu Authors
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2023 HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: '3.8'
services:
  website:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ../:/work/opentofu-repo/main
    command:
      - npm
      - run
      - build
    restart: no